"""
Django settings for unsubscribeapp project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-s=^1u2^u@m#04e4wdg!a$7l4eb1_llj0te&&+ugi4jo6$!e-5+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "unsubscribe-app-57bda8f4af9c.herokuapp.com",
    "127.0.0.1",

    # SVE "unsub..." domene – root, wildcard i www
    "unsubadios.site",
    ".unsubadios.site",
    "www.unsubadios.site",
    "unsubbeoff.site",
    ".unsubbeoff.site",
    "www.unsubbeoff.site",
    "unsubbyebye.site",
    ".unsubbyebye.site",
    "www.unsubbyebye.site",
    "unsubfinal.site",
    ".unsubfinal.site",
    "www.unsubfinal.site",
    "unsubfreeus.site",
    ".unsubfreeus.site",
    "www.unsubfreeus.site",
    "unsubgetlost.site",
    ".unsubgetlost.site",
    "www.unsubgetlost.site",
    "unsubgoaway.site",
    ".unsubgoaway.site",
    "www.unsubgoaway.site",
    "unsubgobye.site",
    ".unsubgobye.site",
    "www.unsubgobye.site",
    "unsubgonow.site",
    ".unsubgonow.site",
    "www.unsubgonow.site",
    "unsubletgo.site",
    ".unsubletgo.site",
    "www.unsubletgo.site",
    "unsubnospam.site",
    ".unsubnospam.site",
    "www.unsubnospam.site",
    "unsubnothere.site",
    ".unsubnothere.site",
    "www.unsubnothere.site",
    "unsubnotime.site",
    ".unsubnotime.site",
    "www.unsubnotime.site",
    "unsuboutnow.site",
    ".unsuboutnow.site",
    "www.unsuboutnow.site",
    "unsubseeyou.site",
    ".unsubseeyou.site",
    "www.unsubseeyou.site",
  
    # Ostale stare domene – root, wildcard i www
    "emaildelete.xyz",
    ".emaildelete.xyz",
    "www.emaildelete.xyz",
    "removeme.online",
    ".removeme.online",
    "www.removeme.online",
    "unsubai.space",
    ".unsubai.space",
    "www.unsubai.space",
    "cobradel.online",
    ".cobradel.online",
    "www.cobradel.online",
    "levelingunsub.xyz",
    ".levelingunsub.xyz",
    "www.levelingunsub.xyz",
    "loomify360.com",
    ".loomify360.com",
    "www.loomify360.com",
    "voyageharbor.com",
    ".voyageharbor.com",
    "www.voyageharbor.com",

    # NOVE DOMENE – root, wildcard i www
    "mncunsubme.online",
    ".mncunsubme.online",
    "www.mncunsubme.online",
    "mncunsubme.store",
    ".mncunsubme.store",
    "www.mncunsubme.store",
    "munsubey.online",
    ".munsubey.online",
    "www.munsubey.online",
    "munsubey.store",
    ".munsubey.store",
    "www.munsubey.store",
    "myncunsubee.online",
    ".myncunsubee.online",
    "www.myncunsubee.online",
    "myncunsubee.store",
    ".myncunsubee.store",
    "www.myncunsubee.store",
    "myncunsubme.online",
    ".myncunsubme.online",
    "www.myncunsubme.online",
    "myncunsubme.store",
    ".myncunsubme.store",
    "www.myncunsubme.store",
    "myunsubne.online",
    ".myunsubne.online",
    "www.myunsubne.online",
    "myunsubne.store",
    ".myunsubne.store",
    "www.myunsubne.store",

    # DODANE DOMENE – root, wildcard i www
    "link-for-unsubscribe.site",
    ".link-for-unsubscribe.site",
    "www.link-for-unsubscribe.site",
    "unsubscribe-now.site",
    ".unsubscribe-now.site",
    "www.unsubscribe-now.site",
    "clean-inbox.site",
    ".clean-inbox.site",
    "www.clean-inbox.site",
    "mail-settings.site",
    ".mail-settings.site",
    "www.mail-settings.site",
    "prefs-manager.site",
    ".prefs-manager.site",
    "www.prefs-manager.site",
    "list-control.site",
    ".list-control.site",
    "www.list-control.site",
    "optout-center.site",
    ".optout-center.site",
    "www.optout-center.site",
    "manage-preferences.site",
    ".manage-preferences.site",
    "www.manage-preferences.site",
    "stop-my-mails.site",
    ".stop-my-mails.site",
    "www.stop-my-mails.site",
    "unsubscribe-hub.site",
    ".unsubscribe-hub.site",
    "www.unsubscribe-hub.site",

    # NOVO DODANO – root, wildcard i www
    "unsubto.site",
    ".unsubto.site",
    "www.unsubto.site",
    "unsubenzihere.site",
    ".unsubenzihere.site",
    "www.unsubenzihere.site",
    "unsubthere.site",
    ".unsubthere.site",
    "www.unsubthere.site",
    "unsublowhp.site",
    ".unsublowhp.site",
    "www.unsublowhp.site",
    "unsubheal.site",
    ".unsubheal.site",
    "www.unsubheal.site",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'unsubscribeapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unsubscribeapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'daecv5i5qj0c86',
        'USER': 'u1tu9dioooo5ba',
        'PASSWORD': 'pbedb6f2fcbf6efe2f5b5ae52ddf9e304c31c8795dddc62faf1b098dcb6a596ef',
        'HOST': 'c3b50so8id8nre.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com',  # Or an IP Address that your DB is hosted on
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Define the directories where Django should look for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # This assumes 'static' is at the top level of your project
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SECRET_KEY = os.environ.get('SECRET_KEY', 'cg#p$g+j9tax!#a3cup@1$8obt2_+&k3q+pmu)5%asj6yjpkag')

